import { AppDataSource } from './database.js';
import { Session } from './entities/Session.js';

const getDateString = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
};

const getTimeString = (hour: number, minute: number = 0): string => {
  const date = new Date();
  date.setHours(hour, minute);
  return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
};

export async function seedSessionsData() {
  const sessionRepo = AppDataSource.getRepository(Session);

  const existingCount = await sessionRepo.count();
  if (existingCount > 0) {
    console.log(`🗑️  Deleting ${existingCount} existing sessions...`);
    const allSessions = await sessionRepo.find();
    await sessionRepo.remove(allSessions);
  }

  const sessions = [
    // ========== MINDSET SESSIONS ==========
    {
      title: 'Morning Mindset Ritual: Start Your Day Right',
      description: 'Transform your mornings with proven mindset practices. Learn how successful entrepreneurs and athletes prime their minds for peak performance. This interactive session covers gratitude practices, visualization techniques, and mental preparation strategies.',
      type: 'Meditation',
      category: 'Mindset',
      date: getDateString(1),
      time: getTimeString(6, 30),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773',
      hostId: 'host_1',
      hostName: 'Sarah Thompson',
      hostAvatar: 'https://i.pravatar.cc/150?u=sarah',
      hostBio: 'Mindfulness coach with 10+ years experience. Former tech executive turned wellness advocate.',
      topics: ['Morning Routine', 'Visualization', 'Gratitude Practice', 'Mental Clarity'],
      learningOutcomes: [
        'Create a personalized morning ritual',
        'Master visualization techniques',
        'Build a sustainable gratitude practice',
        'Develop mental clarity and focus'
      ],
      tags: ['meditation', 'morning routine', 'mindfulness', 'peak performance'],
      maxParticipants: 50,
      currentRSVPs: 34,
      zoomLink: 'https://zoom.us/j/12345',
      zoomMeetingId: '123 456 7890',
      zoomPasscode: 'mindset',
      durationMinutes: 45,
      difficulty: 'Beginner' as const,
      featured: true,
    },
    {
      title: 'Overcoming Imposter Syndrome',
      description: 'Break free from self-doubt and step into your power. This masterclass explores the psychology of imposter syndrome and provides practical tools to build authentic confidence. Perfect for professionals, creators, and anyone feeling "not good enough".',
      type: 'Masterclass',
      category: 'Mindset',
      date: getDateString(3),
      time: getTimeString(19, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f',
      hostId: 'host_2',
      hostName: 'Dr. Michael Chen',
      hostAvatar: 'https://i.pravatar.cc/150?u=michael',
      hostBio: 'Clinical psychologist specializing in performance psychology and cognitive behavioral therapy.',
      topics: ['Imposter Syndrome', 'Self-Confidence', 'Cognitive Reframing', 'Identity Work'],
      learningOutcomes: [
        'Understand the root causes of imposter syndrome',
        'Learn cognitive reframing techniques',
        'Build evidence-based self-confidence',
        'Create an action plan for authentic growth'
      ],
      tags: ['psychology', 'confidence', 'career', 'personal growth'],
      maxParticipants: 100,
      currentRSVPs: 78,
      zoomLink: 'https://zoom.us/j/23456',
      durationMinutes: 90,
      difficulty: 'Intermediate' as const,
      featured: true,
    },
    {
      title: 'Stoic Philosophy for Modern Life',
      description: 'Ancient wisdom meets modern challenges. Explore Stoic principles and how to apply them to daily life challenges. Learn from Marcus Aurelius, Epictetus, and Seneca to build resilience and inner peace.',
      type: 'Workshop',
      category: 'Mindset',
      date: getDateString(5),
      time: getTimeString(18, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1544731612-de7f96afe55f',
      hostId: 'host_3',
      hostName: 'James Morrison',
      hostAvatar: 'https://i.pravatar.cc/150?u=james',
      hostBio: 'Philosophy professor and author of "Stoicism in the 21st Century".',
      topics: ['Stoicism', 'Resilience', 'Emotional Control', 'Philosophy'],
      learningOutcomes: [
        'Understand core Stoic principles',
        'Apply dichotomy of control to daily challenges',
        'Develop emotional resilience',
        'Build a personal philosophy'
      ],
      tags: ['philosophy', 'stoicism', 'resilience', 'wisdom'],
      maxParticipants: 60,
      currentRSVPs: 42,
      zoomLink: 'https://zoom.us/j/34567',
      durationMinutes: 75,
      difficulty: 'Intermediate' as const,
      featured: false,
    },

    // ========== PRODUCTIVITY SESSIONS ==========
    {
      title: 'Deep Work Protocol: 4-Hour Focus Blocks',
      description: 'Master the art of deep work and 10x your output. Learn Cal Newport\'s proven strategies for achieving flow state and eliminating distractions. Includes live implementation session.',
      type: 'Workshop',
      category: 'Productivity',
      date: getDateString(2),
      time: getTimeString(14, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b',
      hostId: 'host_4',
      hostName: 'Alex Rivera',
      hostAvatar: 'https://i.pravatar.cc/150?u=alex',
      hostBio: 'Productivity consultant who helped 500+ professionals double their output.',
      topics: ['Deep Work', 'Time Blocking', 'Focus', 'Flow State'],
      learningOutcomes: [
        'Create your deep work schedule',
        'Build a distraction-free environment',
        'Master the 4-hour focus block',
        'Track and optimize your deep work hours'
      ],
      tags: ['productivity', 'focus', 'time management', 'deep work'],
      maxParticipants: 80,
      currentRSVPs: 65,
      zoomLink: 'https://zoom.us/j/45678',
      durationMinutes: 120,
      difficulty: 'Advanced' as const,
      featured: true,
    },
    {
      title: 'GTD 2.0: Getting Things Done for Digital Natives',
      description: 'The complete Getting Things Done system, modernized for the digital age. Learn to capture, clarify, organize, reflect, and engage with your work. Includes template library and automation setup.',
      type: 'Masterclass',
      category: 'Productivity',
      date: getDateString(4),
      time: getTimeString(10, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40',
      hostId: 'host_5',
      hostName: 'Emily Watson',
      hostAvatar: 'https://i.pravatar.cc/150?u=emily',
      hostBio: 'Certified GTD coach and productivity systems architect.',
      topics: ['GTD', 'Task Management', 'Workflow', 'Organization'],
      learningOutcomes: [
        'Build your complete GTD system',
        'Master the 5 steps of GTD',
        'Implement digital GTD tools',
        'Achieve "mind like water" clarity'
      ],
      tags: ['gtd', 'organization', 'workflow', 'systems'],
      maxParticipants: 70,
      currentRSVPs: 53,
      zoomLink: 'https://zoom.us/j/56789',
      durationMinutes: 90,
      difficulty: 'Intermediate' as const,
      featured: false,
    },
    {
      title: 'Time Blocking Masterclass',
      description: 'Stop reactive living, start intentional designing. Learn to plan your ideal week and protect your most important hours. Includes the Time Blocking Planner template.',
      type: 'Masterclass',
      category: 'Productivity',
      date: getDateString(6),
      time: getTimeString(20, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe',
      hostId: 'host_6',
      hostName: 'David Park',
      hostAvatar: 'https://i.pravatar.cc/150?u=david',
      hostBio: 'Time management expert featured in Forbes, Inc, and Entrepreneur.',
      topics: ['Time Blocking', 'Calendar Management', 'Prioritization', 'Planning'],
      learningOutcomes: [
        'Design your ideal week',
        'Master time blocking principles',
        'Protect your maker time',
        'Handle interruptions gracefully'
      ],
      tags: ['time blocking', 'calendar', 'planning', 'scheduling'],
      maxParticipants: 90,
      currentRSVPs: 71,
      zoomLink: 'https://zoom.us/j/67890',
      durationMinutes: 60,
      difficulty: 'Beginner' as const,
      featured: false,
    },

    // ========== HEALTH & FITNESS SESSIONS ==========
    {
      title: 'HIIT at Home: 30-Minute Fat Burn',
      description: 'High-intensity interval training that requires zero equipment. Burn 400+ calories in 30 minutes with proven exercises. All fitness levels welcome.',
      type: 'Workshop',
      category: 'Health',
      date: getDateString(1),
      time: getTimeString(7, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438',
      hostId: 'host_7',
      hostName: 'Coach Marcus Lee',
      hostAvatar: 'https://i.pravatar.cc/150?u=marcus',
      hostBio: 'Certified personal trainer with 15 years experience. Former Olympic athlete.',
      topics: ['HIIT', 'Cardio', 'Fat Loss', 'Home Workout'],
      learningOutcomes: [
        'Master HIIT fundamentals',
        'Learn 20+ bodyweight exercises',
        'Build your custom HIIT routine',
        'Track workout intensity'
      ],
      tags: ['fitness', 'hiit', 'workout', 'health'],
      maxParticipants: 150,
      currentRSVPs: 127,
      zoomLink: 'https://zoom.us/j/78901',
      durationMinutes: 30,
      difficulty: 'Beginner' as const,
      featured: true,
    },
    {
      title: 'Sleep Optimization: The Ultimate Guide',
      description: 'Transform your sleep and wake up energized. Evidence-based strategies for better sleep quality, including circadian rhythm optimization, sleep environment design, and supplementation.',
      type: 'Masterclass',
      category: 'Health',
      date: getDateString(3),
      time: getTimeString(21, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55',
      hostId: 'host_8',
      hostName: 'Dr. Lisa Chang',
      hostAvatar: 'https://i.pravatar.cc/150?u=lisa',
      hostBio: 'Sleep specialist and neuroscientist. Author of "The Sleep Solution".',
      topics: ['Sleep', 'Circadian Rhythm', 'Recovery', 'Energy'],
      learningOutcomes: [
        'Optimize your sleep environment',
        'Master circadian rhythm principles',
        'Create your sleep protocol',
        'Track and improve sleep quality'
      ],
      tags: ['sleep', 'health', 'recovery', 'energy'],
      maxParticipants: 100,
      currentRSVPs: 82,
      zoomLink: 'https://zoom.us/j/89012',
      durationMinutes: 75,
      difficulty: 'Intermediate' as const,
      featured: true,
    },
    {
      title: 'Nutrition Fundamentals: Macros Made Simple',
      description: 'Cut through the confusion and learn what actually matters for nutrition. Understand macros, meal timing, and how to eat for your goals without restrictive diets.',
      type: 'Workshop',
      category: 'Health',
      date: getDateString(5),
      time: getTimeString(17, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061',
      hostId: 'host_9',
      hostName: 'Nutritionist Sarah Kim',
      hostAvatar: 'https://i.pravatar.cc/150?u=sarahkim',
      hostBio: 'Registered dietitian and sports nutritionist.',
      topics: ['Nutrition', 'Macros', 'Meal Planning', 'Health'],
      learningOutcomes: [
        'Understand macronutrients',
        'Calculate your macro targets',
        'Build flexible meal plans',
        'Track nutrition effectively'
      ],
      tags: ['nutrition', 'diet', 'health', 'macros'],
      maxParticipants: 80,
      currentRSVPs: 59,
      zoomLink: 'https://zoom.us/j/90123',
      durationMinutes: 60,
      difficulty: 'Beginner' as const,
      featured: false,
    },

    // ========== BUSINESS SESSIONS ==========
    {
      title: 'Side Hustle Sprint: $1K in 30 Days',
      description: 'Launch your first side hustle and make your first $1,000. Learn validated business models, how to find your first customers, and pricing strategies that work.',
      type: 'Masterclass',
      category: 'Business',
      date: getDateString(2),
      time: getTimeString(19, 30),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
      hostId: 'host_10',
      hostName: 'Jake Anderson',
      hostAvatar: 'https://i.pravatar.cc/150?u=jake',
      hostBio: 'Built 3 successful online businesses from scratch. Total revenue: $2M+.',
      topics: ['Entrepreneurship', 'Side Hustle', 'Business', 'Revenue'],
      learningOutcomes: [
        'Choose your side hustle model',
        'Find your first paying customers',
        'Set profitable pricing',
        'Build your launch plan'
      ],
      tags: ['business', 'entrepreneurship', 'side hustle', 'money'],
      maxParticipants: 120,
      currentRSVPs: 103,
      zoomLink: 'https://zoom.us/j/01234',
      durationMinutes: 90,
      difficulty: 'Beginner' as const,
      featured: true,
    },
    {
      title: 'Personal Branding on LinkedIn',
      description: 'Build a magnetic personal brand that attracts opportunities. Learn content strategy, profile optimization, and engagement tactics that converted my LinkedIn into $500K+ in business.',
      type: 'Workshop',
      category: 'Business',
      date: getDateString(4),
      time: getTimeString(18, 30),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1611944212129-29977ae1398c',
      hostId: 'host_11',
      hostName: 'Rachel Foster',
      hostAvatar: 'https://i.pravatar.cc/150?u=rachel',
      hostBio: 'LinkedIn strategist with 100K+ followers. Helped 200+ clients land dream jobs.',
      topics: ['LinkedIn', 'Personal Branding', 'Content', 'Networking'],
      learningOutcomes: [
        'Optimize your LinkedIn profile',
        'Create engaging content',
        'Build strategic connections',
        'Generate inbound opportunities'
      ],
      tags: ['linkedin', 'personal branding', 'content', 'career'],
      maxParticipants: 90,
      currentRSVPs: 76,
      zoomLink: 'https://zoom.us/j/12340',
      durationMinutes: 75,
      difficulty: 'Intermediate' as const,
      featured: false,
    },
    {
      title: 'Freelancing Freedom: Your First Clients',
      description: 'Go from employed to freelance in 30 days. Learn how to position yourself, find clients on Upwork/Fiverr, write winning proposals, and close your first deals.',
      type: 'Masterclass',
      category: 'Business',
      date: getDateString(7),
      time: getTimeString(16, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
      hostId: 'host_12',
      hostName: 'Tom Bradford',
      hostAvatar: 'https://i.pravatar.cc/150?u=tom',
      hostBio: 'Former corporate slave, now 6-figure freelancer working 20 hours/week.',
      topics: ['Freelancing', 'Client Acquisition', 'Proposals', 'Career'],
      learningOutcomes: [
        'Choose your freelance niche',
        'Set up winning profiles',
        'Write proposals that convert',
        'Close your first 3 clients'
      ],
      tags: ['freelancing', 'remote work', 'career', 'business'],
      maxParticipants: 100,
      currentRSVPs: 87,
      zoomLink: 'https://zoom.us/j/23401',
      durationMinutes: 90,
      difficulty: 'Beginner' as const,
      featured: false,
    },

    // ========== RELATIONSHIPS SESSIONS ==========
    {
      title: 'Communication Mastery for Couples',
      description: 'Transform your relationship with better communication. Learn active listening, non-violent communication, and conflict resolution skills that actually work.',
      type: 'Workshop',
      category: 'Relationships',
      date: getDateString(3),
      time: getTimeString(20, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2',
      hostId: 'host_13',
      hostName: 'Dr. Jennifer Lopez',
      hostAvatar: 'https://i.pravatar.cc/150?u=jennifer',
      hostBio: 'Marriage counselor with 20+ years experience. Saved 1000+ relationships.',
      topics: ['Communication', 'Relationships', 'Conflict Resolution', 'Love'],
      learningOutcomes: [
        'Master active listening',
        'Express needs without blame',
        'Resolve conflicts constructively',
        'Build deeper intimacy'
      ],
      tags: ['relationships', 'communication', 'couples', 'love'],
      maxParticipants: 60,
      currentRSVPs: 48,
      zoomLink: 'https://zoom.us/j/34012',
      durationMinutes: 90,
      difficulty: 'Intermediate' as const,
      featured: false,
    },
    {
      title: 'Networking Without the Awkward',
      description: 'Build genuine connections without feeling salesy. Learn authentic networking strategies for introverts and anyone who hates "networking events".',
      type: 'Workshop',
      category: 'Relationships',
      date: getDateString(5),
      time: getTimeString(19, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18',
      hostId: 'host_14',
      hostName: 'Mark Johnson',
      hostAvatar: 'https://i.pravatar.cc/150?u=mark',
      hostBio: 'Introvert who built a 10K+ person network. Author of "Authentic Networking".',
      topics: ['Networking', 'Relationships', 'Social Skills', 'Career'],
      learningOutcomes: [
        'Network as an introvert',
        'Build authentic connections',
        'Follow up effectively',
        'Turn contacts into friendships'
      ],
      tags: ['networking', 'social skills', 'relationships', 'career'],
      maxParticipants: 80,
      currentRSVPs: 63,
      zoomLink: 'https://zoom.us/j/45123',
      durationMinutes: 60,
      difficulty: 'Beginner' as const,
      featured: false,
    },
    {
      title: 'Boundaries: The Art of Saying No',
      description: 'Protect your time, energy, and peace. Learn to set healthy boundaries in work, family, and friendships without guilt or fear of rejection.',
      type: 'Masterclass',
      category: 'Relationships',
      date: getDateString(8),
      time: getTimeString(18, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173',
      hostId: 'host_15',
      hostName: 'Dr. Amanda White',
      hostAvatar: 'https://i.pravatar.cc/150?u=amanda',
      hostBio: 'Clinical psychologist specializing in boundaries and assertiveness training.',
      topics: ['Boundaries', 'Assertiveness', 'Self-Care', 'Relationships'],
      learningOutcomes: [
        'Identify boundary violations',
        'Say no with confidence',
        'Handle pushback gracefully',
        'Build self-respect'
      ],
      tags: ['boundaries', 'self-care', 'assertiveness', 'psychology'],
      maxParticipants: 70,
      currentRSVPs: 54,
      zoomLink: 'https://zoom.us/j/56234',
      durationMinutes: 75,
      difficulty: 'Intermediate' as const,
      featured: false,
    },

    // ========== FINANCE SESSIONS ==========
    {
      title: 'Budgeting 101: Take Control of Your Money',
      description: 'Finally understand where your money goes. Learn zero-based budgeting, automate your finances, and build your first $1000 emergency fund.',
      type: 'Workshop',
      category: 'Finance',
      date: getDateString(2),
      time: getTimeString(18, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e',
      hostId: 'host_16',
      hostName: 'Financial Coach Chris',
      hostAvatar: 'https://i.pravatar.cc/150?u=chris',
      hostBio: 'Helped 500+ people pay off $5M+ in debt and build wealth.',
      topics: ['Budgeting', 'Money Management', 'Savings', 'Finance'],
      learningOutcomes: [
        'Create your zero-based budget',
        'Track expenses effectively',
        'Automate your finances',
        'Build your emergency fund'
      ],
      tags: ['budgeting', 'money', 'finance', 'savings'],
      maxParticipants: 100,
      currentRSVPs: 79,
      zoomLink: 'https://zoom.us/j/67345',
      durationMinutes: 75,
      difficulty: 'Beginner' as const,
      featured: true,
    },
    {
      title: 'Investing for Beginners: Index Funds & ETFs',
      description: 'Start investing with confidence. Learn about index funds, ETFs, asset allocation, and how to build a simple portfolio that beats 90% of professionals.',
      type: 'Masterclass',
      category: 'Finance',
      date: getDateString(4),
      time: getTimeString(19, 30),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3',
      hostId: 'host_17',
      hostName: 'Investment Advisor Maya',
      hostAvatar: 'https://i.pravatar.cc/150?u=maya',
      hostBio: 'CFP with 15 years experience. Manages $50M+ in client assets.',
      topics: ['Investing', 'Index Funds', 'ETFs', 'Wealth Building'],
      learningOutcomes: [
        'Understand investing basics',
        'Choose the right index funds',
        'Build your portfolio',
        'Automate your investments'
      ],
      tags: ['investing', 'index funds', 'etfs', 'wealth'],
      maxParticipants: 120,
      currentRSVPs: 98,
      zoomLink: 'https://zoom.us/j/78456',
      durationMinutes: 90,
      difficulty: 'Beginner' as const,
      featured: true,
    },
    {
      title: 'Debt Payoff Strategy: Snowball vs Avalanche',
      description: 'Create your debt freedom plan. Compare payoff strategies, negotiate with creditors, and build momentum to become debt-free in 12-36 months.',
      type: 'Workshop',
      category: 'Finance',
      date: getDateString(6),
      time: getTimeString(20, 30),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1554224311-beee4ead2d86',
      hostId: 'host_18',
      hostName: 'Debt Coach Ryan',
      hostAvatar: 'https://i.pravatar.cc/150?u=ryan',
      hostBio: 'Paid off $100K in debt in 3 years. Now helping others do the same.',
      topics: ['Debt', 'Debt Payoff', 'Money Management', 'Finance'],
      learningOutcomes: [
        'Choose your payoff strategy',
        'Negotiate better rates',
        'Find extra money in your budget',
        'Build your debt-free plan'
      ],
      tags: ['debt', 'finance', 'money', 'freedom'],
      maxParticipants: 80,
      currentRSVPs: 62,
      zoomLink: 'https://zoom.us/j/89567',
      durationMinutes: 60,
      difficulty: 'Intermediate' as const,
      featured: false,
    },

    // ========== PERSONAL GROWTH SESSIONS ==========
    {
      title: 'Goal Setting That Actually Works',
      description: 'Set goals you\'ll actually achieve. Learn the SMART framework, implementation intentions, and accountability systems that turn dreams into reality.',
      type: 'Workshop',
      category: 'Personal Growth',
      date: getDateString(1),
      time: getTimeString(17, 0),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b',
      hostId: 'host_19',
      hostName: 'Success Coach Maria',
      hostAvatar: 'https://i.pravatar.cc/150?u=maria',
      hostBio: 'Performance coach who helped 1000+ people achieve their biggest goals.',
      topics: ['Goal Setting', 'Planning', 'Achievement', 'Success'],
      learningOutcomes: [
        'Set SMART goals',
        'Create implementation plans',
        'Build accountability systems',
        'Track and adjust goals'
      ],
      tags: ['goals', 'planning', 'success', 'achievement'],
      maxParticipants: 90,
      currentRSVPs: 73,
      zoomLink: 'https://zoom.us/j/90678',
      durationMinutes: 75,
      difficulty: 'Beginner' as const,
      featured: false,
    },
    {
      title: 'Habits: The Compound Effect',
      description: 'Small habits, massive results. Learn the science of habit formation, how to stack habits, and build systems that make success inevitable. Based on Atomic Habits principles.',
      type: 'Masterclass',
      category: 'Personal Growth',
      date: getDateString(3),
      time: getTimeString(18, 30),
      status: 'Upcoming' as const,
      image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173',
      hostId: 'host_20',
      hostName: 'James Wilson',
      hostAvatar: 'https://i.pravatar.cc/150?u=jameswilson',
      hostBio: 'Habit formation expert. Built and maintained 50+ daily habits for 5 years.',
      topics: ['Habits', 'Behavior Change', 'Systems', 'Compound Effect'],
      learningOutcomes: [
        'Understand habit psychology',
        'Design habit systems',
        'Stack habits effectively',
        'Track and maintain habits'
      ],
      tags: ['habits', 'behavior change', 'personal growth', 'systems'],
      maxParticipants: 110,
      currentRSVPs: 94,
      zoomLink: 'https://zoom.us/j/01789',
      durationMinutes: 90,
      difficulty: 'Intermediate' as const,
      featured: true,
    },

    // ========== LIVE SESSIONS ==========
    {
      title: '🔴 LIVE: Q&A with Peak Performance Coach',
      description: 'Join us LIVE right now! Ask your burning questions about productivity, habits, mindset, and achieving your goals. Interactive session with real-time coaching.',
      type: 'Q&A',
      category: 'Personal Growth',
      date: 'Today',
      time: 'Now',
      status: 'Live' as const,
      image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2',
      hostId: 'host_21',
      hostName: 'Coach Tony Robbins',
      hostAvatar: 'https://i.pravatar.cc/150?u=tony',
      hostBio: 'International speaker and peak performance strategist.',
      topics: ['Q&A', 'Coaching', 'Personal Growth', 'Live'],
      learningOutcomes: [
        'Get answers to your questions',
        'Receive personalized coaching',
        'Connect with community',
        'Take immediate action'
      ],
      tags: ['live', 'qna', 'coaching', 'interactive'],
      maxParticipants: 200,
      currentRSVPs: 156,
      zoomLink: 'https://zoom.us/j/12890',
      durationMinutes: 60,
      difficulty: 'Beginner' as const,
      featured: true,
    },
    {
      title: '🔴 LIVE: Guided Meditation - Stress Relief',
      description: 'Join us NOW for a calming guided meditation. Release stress, find inner peace, and recharge your energy. Perfect for your lunch break or evening wind-down.',
      type: 'Meditation',
      category: 'Mindset',
      date: 'Today',
      time: 'Now',
      status: 'Live' as const,
      image: 'https://images.unsplash.com/photo-1545389336-cf090694435e',
      hostId: 'host_22',
      hostName: 'Meditation Guide Luna',
      hostAvatar: 'https://i.pravatar.cc/150?u=luna',
      hostBio: 'Certified meditation teacher with 10,000+ guided sessions.',
      topics: ['Meditation', 'Stress Relief', 'Mindfulness', 'Relaxation'],
      learningOutcomes: [
        'Release stress and tension',
        'Find inner calm',
        'Recharge your energy',
        'Practice daily meditation'
      ],
      tags: ['meditation', 'live', 'stress relief', 'mindfulness'],
      maxParticipants: 100,
      currentRSVPs: 78,
      zoomLink: 'https://zoom.us/j/23891',
      durationMinutes: 20,
      difficulty: 'Beginner' as const,
      featured: false,
    },

    // ========== PAST SESSIONS WITH RECORDINGS ==========
    {
      title: 'The Science of Motivation',
      description: 'Understand what drives human behavior. Learn about intrinsic vs extrinsic motivation, the dopamine system, and how to stay motivated long-term.',
      type: 'Masterclass',
      category: 'Mindset',
      date: 'December 1, 2024',
      time: '7:00 PM',
      status: 'Past' as const,
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
      hostId: 'host_23',
      hostName: 'Dr. Andrew Huberman',
      hostAvatar: 'https://i.pravatar.cc/150?u=huberman',
      hostBio: 'Neuroscientist and professor at Stanford School of Medicine.',
      topics: ['Motivation', 'Neuroscience', 'Behavior', 'Psychology'],
      learningOutcomes: [
        'Understand motivation science',
        'Leverage dopamine effectively',
        'Build intrinsic motivation',
        'Sustain long-term drive'
      ],
      tags: ['neuroscience', 'motivation', 'science', 'psychology'],
      maxParticipants: 150,
      currentRSVPs: 150,
      recordingUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      durationMinutes: 120,
      difficulty: 'Advanced' as const,
      featured: false,
    },
    {
      title: 'Building a Second Brain',
      description: 'Master personal knowledge management. Learn Tiago Forte\'s PARA method, how to capture ideas, and build your external brain using Notion, Obsidian, or Roam.',
      type: 'Workshop',
      category: 'Productivity',
      date: 'November 28, 2024',
      time: '6:00 PM',
      status: 'Past' as const,
      image: 'https://images.unsplash.com/photo-1558403194-611308249627',
      hostId: 'host_24',
      hostName: 'Tiago Forte',
      hostAvatar: 'https://i.pravatar.cc/150?u=tiago',
      hostBio: 'Author of "Building a Second Brain". Productivity expert.',
      topics: ['PKM', 'Note Taking', 'Knowledge Management', 'Productivity'],
      learningOutcomes: [
        'Implement PARA method',
        'Build your second brain',
        'Capture and organize ideas',
        'Retrieve knowledge easily'
      ],
      tags: ['pkm', 'productivity', 'note taking', 'knowledge'],
      maxParticipants: 100,
      currentRSVPs: 100,
      recordingUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      durationMinutes: 90,
      difficulty: 'Intermediate' as const,
      featured: true,
    },
    {
      title: 'Intermittent Fasting 101',
      description: 'Learn the science and practice of intermittent fasting. Understand different protocols (16:8, 20:4, OMAD), benefits, and how to start safely.',
      type: 'Workshop',
      category: 'Health',
      date: 'November 25, 2024',
      time: '5:00 PM',
      status: 'Past' as const,
      image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061',
      hostId: 'host_25',
      hostName: 'Dr. Jason Fung',
      hostAvatar: 'https://i.pravatar.cc/150?u=fung',
      hostBio: 'Nephrologist and IF expert. Author of "The Obesity Code".',
      topics: ['Fasting', 'Nutrition', 'Health', 'Weight Loss'],
      learningOutcomes: [
        'Understand IF science',
        'Choose your IF protocol',
        'Start fasting safely',
        'Track your progress'
      ],
      tags: ['fasting', 'nutrition', 'health', 'diet'],
      maxParticipants: 120,
      currentRSVPs: 120,
      recordingUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      durationMinutes: 75,
      difficulty: 'Beginner' as const,
      featured: false,
    },
    {
      title: 'Copywriting that Converts',
      description: 'Write copy that sells. Learn proven frameworks (PAS, AIDA, FAB), headline formulas, and how to craft compelling sales pages and emails.',
      type: 'Masterclass',
      category: 'Business',
      date: 'November 22, 2024',
      time: '7:30 PM',
      status: 'Past' as const,
      image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a',
      hostId: 'host_26',
      hostName: 'Copywriter Alex',
      hostAvatar: 'https://i.pravatar.cc/150?u=alexcopy',
      hostBio: '$10M+ in client sales. Copywriter for Fortune 500 companies.',
      topics: ['Copywriting', 'Marketing', 'Sales', 'Business'],
      learningOutcomes: [
        'Master copywriting frameworks',
        'Write magnetic headlines',
        'Craft sales pages',
        'Increase conversions'
      ],
      tags: ['copywriting', 'marketing', 'sales', 'writing'],
      maxParticipants: 90,
      currentRSVPs: 90,
      recordingUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      durationMinutes: 120,
      difficulty: 'Advanced' as const,
      featured: false,
    },
    {
      title: 'Public Speaking Mastery',
      description: 'Overcome fear and speak with confidence. Learn speech structure, delivery techniques, and how to engage any audience. Includes live practice session.',
      type: 'Workshop',
      category: 'Personal Growth',
      date: 'November 20, 2024',
      time: '6:30 PM',
      status: 'Past' as const,
      image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2',
      hostId: 'host_27',
      hostName: 'Speaker Coach Emma',
      hostAvatar: 'https://i.pravatar.cc/150?u=emma',
      hostBio: 'TEDx speaker coach. Helped 500+ people deliver powerful talks.',
      topics: ['Public Speaking', 'Communication', 'Confidence', 'Presentation'],
      learningOutcomes: [
        'Overcome speaking fear',
        'Structure powerful speeches',
        'Master delivery techniques',
        'Engage your audience'
      ],
      tags: ['public speaking', 'communication', 'confidence', 'presentation'],
      maxParticipants: 70,
      currentRSVPs: 70,
      recordingUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      durationMinutes: 90,
      difficulty: 'Intermediate' as const,
      featured: false,
    },
  ];

  console.log('🌱 Seeding sessions...');
  for (const sessionData of sessions) {
    const session = sessionRepo.create(sessionData);
    await sessionRepo.save(session);
  }

  console.log(`✅ Successfully seeded ${sessions.length} sessions`);
}
