import { AppDataSource } from './database.js';
import { BrainTool } from './entities/BrainTool.js';
import { ResourceBook } from './entities/ResourceBook.js';
import { ResourceTemplate } from './entities/ResourceTemplate.js';
import { ResourceMedia } from './entities/ResourceMedia.js';
import { Course } from './entities/Course.js';

export const seedBrainToolsData = async () => {
  const brainToolRepo = AppDataSource.getRepository(BrainTool);
  const bookRepo = AppDataSource.getRepository(ResourceBook);
  const templateRepo = AppDataSource.getRepository(ResourceTemplate);
  const mediaRepo = AppDataSource.getRepository(ResourceMedia);
  const courseRepo = AppDataSource.getRepository(Course);

  // Check if comprehensive data already exists
  const existingToolsCount = await brainToolRepo.count();
  const existingBooksCount = await bookRepo.count();
  
  if (existingToolsCount >= 40 && existingBooksCount >= 25) {
    console.log('✅ Comprehensive data already seeded:');
    console.log(`   - ${existingToolsCount} brain tools`);
    console.log(`   - ${existingBooksCount} books`);
    console.log(`   - ${await templateRepo.count()} templates`);
    console.log(`   - ${await mediaRepo.count()} media items`);
    console.log(`   - ${await courseRepo.count()} courses`);
    return;
  }

  // Delete existing minimal data and reseed with comprehensive data
  if (existingToolsCount > 0) {
    console.log('Removing existing minimal data...');
    await brainToolRepo.createQueryBuilder().delete().execute();
    await bookRepo.createQueryBuilder().delete().execute();
    await templateRepo.createQueryBuilder().delete().execute();
    await mediaRepo.createQueryBuilder().delete().execute();
    await courseRepo.createQueryBuilder().delete().execute();
  }

  console.log('Seeding comprehensive brain tools and resources...');

  // Seed Brain Tools (42 tools across 8 categories)
  const brainTools = [
    // Nervous System (5 tools)
    {
      toolId: 'breathing',
      name: 'Box Breathing',
      category: 'nervous-system',
      level: 'Beginner',
      duration: '5 min',
      description: 'Navy SEAL breathing technique used by elite forces to stay calm under pressure. Proven to reduce stress hormones within minutes.',
      science: 'Activates parasympathetic nervous system, reduces cortisol by 25%',
      icon: 'Wind',
      color: 'emerald',
      config: { cycles: 4, inhale: 4, hold1: 4, exhale: 4, hold2: 4 },
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'grounding',
      name: '5-4-3-2-1 Grounding',
      category: 'nervous-system',
      level: 'Beginner',
      duration: '3 min',
      description: 'Rapid anxiety reduction through sensory awareness. Used by therapists worldwide for panic attacks.',
      science: 'Sensory anchoring reduces cortisol, redirects amygdala activation',
      icon: 'Target',
      color: 'emerald',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'body-scan',
      name: 'Body Scan Meditation',
      category: 'nervous-system',
      level: 'Intermediate',
      duration: '10 min',
      description: 'Systematic body awareness practice from mindfulness-based stress reduction (MBSR) program.',
      science: 'Progressive muscle relaxation, decreases muscle tension by 40%',
      icon: 'Heart',
      color: 'emerald',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'cold-exposure',
      name: 'Cold Therapy Protocol',
      category: 'nervous-system',
      level: 'Advanced',
      duration: '2 min',
      description: 'Wim Hof inspired cold exposure for stress resilience. Builds mental toughness and immune function.',
      science: 'Stimulates brown fat activation, increases norepinephrine 530%',
      icon: 'Droplets',
      color: 'emerald',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'hrv-training',
      name: 'Heart Rate Variability Training',
      category: 'nervous-system',
      level: 'Intermediate',
      duration: '15 min',
      description: 'Biofeedback training to increase vagal tone and stress resilience using HRV metrics.',
      science: 'Biofeedback increases vagal tone, predicts stress recovery',
      icon: 'Activity',
      color: 'emerald',
      isActive: true,
      usageCount: 0,
    },

    // Focus & Flow (6 tools)
    {
      toolId: 'pomodoro',
      name: 'Pomodoro Technique',
      category: 'focus-flow',
      level: 'Beginner',
      duration: '25 min',
      description: 'Francesco Cirillo\'s time-boxing method. Breaks work into 25-minute focused intervals with breaks.',
      science: 'Ultradian rhythm optimization, maintains peak cognitive performance',
      icon: 'Timer',
      color: 'blue',
      config: { workMinutes: 25, shortBreak: 5, longBreak: 15, cyclesUntilLongBreak: 4 },
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'deepwork',
      name: 'Deep Work Protocol',
      category: 'focus-flow',
      level: 'Intermediate',
      duration: '90 min',
      description: 'Cal Newport\'s method for distraction-free cognitive work. Achieve flow state for complex tasks.',
      science: 'Attention restoration theory, increases productivity by 400%',
      icon: 'Zap',
      color: 'blue',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'focus-sounds',
      name: 'Binaural Beats Focus',
      category: 'focus-flow',
      level: 'Beginner',
      duration: 'Variable',
      description: '40Hz gamma wave audio for enhanced concentration. Used by students and professionals worldwide.',
      science: 'Neural entrainment synchronizes brainwaves to optimal frequencies',
      icon: 'Headphones',
      color: 'blue',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'environmental-design',
      name: 'Workspace Optimization',
      category: 'focus-flow',
      level: 'Beginner',
      duration: 'Setup',
      description: 'Evidence-based workspace design for maximum productivity. Lighting, temperature, and layout optimization.',
      science: 'Environmental psychology increases performance by 16%',
      icon: 'Lightbulb',
      color: 'blue',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'flowstate',
      name: 'Flow State Induction',
      category: 'focus-flow',
      level: 'Advanced',
      duration: '20 min',
      description: 'Steven Kotler\'s protocol for entering flow. Challenge-skill balance for peak performance.',
      science: 'Releases norepinephrine, dopamine, increases performance 500%',
      icon: 'Flame',
      color: 'blue',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'digital-detox',
      name: 'Digital Detox Timer',
      category: 'focus-flow',
      level: 'Intermediate',
      duration: '60 min',
      description: 'Structured breaks from screens to restore attention. Prevents cognitive fatigue.',
      science: 'Reduces digital eye strain, restores attentional resources',
      icon: 'Zap',
      color: 'blue',
      isActive: true,
      usageCount: 0,
    },

    // Mental Wellness (6 tools)
    {
      toolId: 'cbt',
      name: 'CBT Thought Journal',
      category: 'mental-wellness',
      level: 'Intermediate',
      duration: '10 min',
      description: 'Cognitive Behavioral Therapy exercise to challenge negative automatic thoughts. Evidence-based therapy technique.',
      science: 'Thought restructuring, reduces depression symptoms by 50%',
      icon: 'Brain',
      color: 'purple',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'gratitude',
      name: 'Gratitude Journaling',
      category: 'mental-wellness',
      level: 'Beginner',
      duration: '5 min',
      description: 'Daily practice of writing three things you\'re grateful for. Scientifically proven to increase happiness.',
      science: 'Positive psychology research, increases wellbeing by 25%',
      icon: 'Heart',
      color: 'purple',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'self-compassion',
      name: 'Self-Compassion Practice',
      category: 'mental-wellness',
      level: 'Intermediate',
      duration: '8 min',
      description: 'Kristin Neff\'s self-compassion exercises. Treat yourself with the same kindness you\'d offer a friend.',
      science: 'Reduces self-criticism, increases resilience and motivation',
      icon: 'Heart',
      color: 'purple',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'mindfulness',
      name: 'Mindfulness Training',
      category: 'mental-wellness',
      level: 'Beginner',
      duration: '20 min',
      description: 'Jon Kabat-Zinn\'s MBSR techniques. Present moment awareness without judgment.',
      science: 'MBSR increases gray matter density in hippocampus',
      icon: 'Compass',
      color: 'purple',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'values-clarification',
      name: 'Values Clarification Exercise',
      category: 'mental-wellness',
      level: 'Intermediate',
      duration: '15 min',
      description: 'Identify your core values to guide decision-making. Acceptance and Commitment Therapy technique.',
      science: 'Value-aligned action increases life satisfaction by 30%',
      icon: 'Compass',
      color: 'purple',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'emotional-regulation',
      name: 'Emotional Regulation Skills',
      category: 'mental-wellness',
      level: 'Advanced',
      duration: '12 min',
      description: 'DBT skills for managing intense emotions. TIPP technique for rapid regulation.',
      science: 'Dialectical Behavior Therapy, reduces emotional reactivity',
      icon: 'Heart',
      color: 'purple',
      isActive: true,
      usageCount: 0,
    },

    // Journaling & Reflection (5 tools)
    {
      toolId: 'morning',
      name: 'Morning Intention Setting',
      category: 'journaling',
      level: 'Intermediate',
      duration: '15 min',
      description: 'Set clear intentions for your day. Tim Ferriss\' morning routine practice.',
      science: 'Implementation intentions increase goal achievement by 200%',
      icon: 'Sparkles',
      color: 'amber',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'evening',
      name: 'Evening Reflection',
      category: 'journaling',
      level: 'Beginner',
      duration: '10 min',
      description: 'Daily review practice. What went well? What could improve? Learning from experience.',
      science: 'Experience sampling increases self-awareness and learning',
      icon: 'Compass',
      color: 'amber',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'goal-journal',
      name: 'Goal Achievement Tracking',
      category: 'journaling',
      level: 'Intermediate',
      duration: 'Variable',
      description: 'Weekly goal review and progress tracking. Adjust strategies based on results.',
      science: 'Goal-setting theory, written goals are 42% more likely to be achieved',
      icon: 'Target',
      color: 'amber',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'stream-of-consciousness',
      name: 'Free Writing',
      category: 'journaling',
      level: 'Beginner',
      duration: '20 min',
      description: 'Julia Cameron\'s Morning Pages. Write continuously without editing to unlock creativity.',
      science: 'Automatic writing technique, reduces anxiety and increases clarity',
      icon: 'PenTool',
      color: 'amber',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'weekly-review',
      name: 'Weekly Review Protocol',
      category: 'journaling',
      level: 'Intermediate',
      duration: '30 min',
      description: 'David Allen\'s GTD weekly review. Process inbox, review projects, plan next week.',
      science: 'Regular review reduces cognitive load, increases productivity',
      icon: 'PenTool',
      color: 'amber',
      isActive: true,
      usageCount: 0,
    },

    // Meditation & Mindfulness (5 tools)
    {
      toolId: 'guided-med',
      name: 'Guided Meditation',
      category: 'meditation',
      level: 'Beginner',
      duration: '20 min',
      description: 'Follow along with professional meditation guide. Perfect for beginners.',
      science: 'Default mode network training, increases focus and reduces rumination',
      icon: 'Play',
      color: 'teal',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'breath',
      name: 'Breath Awareness',
      category: 'meditation',
      level: 'Beginner',
      duration: '10 min',
      description: 'Simple breath-focused meditation. Foundation of all mindfulness practices.',
      science: 'Interoceptive awareness, strengthens attention control',
      icon: 'Wind',
      color: 'teal',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'loving-kindness',
      name: 'Loving Kindness Meditation',
      category: 'meditation',
      level: 'Intermediate',
      duration: '15 min',
      description: 'Metta practice from Buddhist tradition. Cultivate compassion for self and others.',
      science: 'Compassion training, increases positive emotions and social connection',
      icon: 'Heart',
      color: 'teal',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'vipassana',
      name: 'Insight Meditation',
      category: 'meditation',
      level: 'Advanced',
      duration: '45 min',
      description: 'Traditional Vipassana practice. Observe sensations without reaction.',
      science: 'Mindfulness-based stress reduction, changes brain structure',
      icon: 'Eye',
      color: 'teal',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'walking-meditation',
      name: 'Walking Meditation',
      category: 'meditation',
      level: 'Beginner',
      duration: '20 min',
      description: 'Mindful walking practice. Meditation in motion for active minds.',
      science: 'Combines movement with mindfulness, reduces stress while energizing',
      icon: 'Activity',
      color: 'teal',
      isActive: true,
      usageCount: 0,
    },

    // Energy & Movement (5 tools)
    {
      toolId: 'power-pose',
      name: 'Power Poses',
      category: 'energy',
      level: 'Beginner',
      duration: '2 min',
      description: 'Amy Cuddy\'s high-power poses. Change your posture to change your mindset.',
      science: 'Body language psychology, increases testosterone and confidence',
      icon: 'Zap',
      color: 'orange',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'stretches',
      name: 'Dynamic Stretching',
      category: 'energy',
      level: 'Beginner',
      duration: '5 min',
      description: 'Active stretching routine to wake up your body. Perfect morning energizer.',
      science: 'Fascia release techniques, increases blood flow and alertness',
      icon: 'Dumbbell',
      color: 'orange',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'cold-plunge',
      name: 'Contrast Therapy',
      category: 'energy',
      level: 'Advanced',
      duration: '10 min',
      description: 'Alternating hot and cold exposure. Elite athlete recovery protocol.',
      science: 'Vasodilation training, reduces inflammation and boosts immunity',
      icon: 'Droplets',
      color: 'orange',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'movement-meditation',
      name: 'Moving Meditation',
      category: 'energy',
      level: 'Intermediate',
      duration: '30 min',
      description: 'Combine gentle movement with mindfulness. Tai Chi and Qigong inspired.',
      science: 'Embodied cognition, integrates mind-body connection',
      icon: 'Activity',
      color: 'orange',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'breathwork-energy',
      name: 'Energizing Breathwork',
      category: 'energy',
      level: 'Intermediate',
      duration: '7 min',
      description: 'Kapalabhati breathing technique for instant energy boost. Coffee alternative.',
      science: 'Increases oxygen, releases epinephrine, energizes within minutes',
      icon: 'Wind',
      color: 'orange',
      isActive: true,
      usageCount: 0,
    },

    // Creativity & Innovation (5 tools)
    {
      toolId: 'creative-visualization',
      name: 'Creative Visualization',
      category: 'creativity',
      level: 'Intermediate',
      duration: '15 min',
      description: 'Mental imagery practice for creative problem-solving. Used by athletes and artists.',
      science: 'Mental imagery research, activates same brain regions as doing',
      icon: 'Eye',
      color: 'rose',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'lateral-thinking',
      name: 'Lateral Thinking Exercises',
      category: 'creativity',
      level: 'Intermediate',
      duration: '20 min',
      description: 'Edward de Bono\'s creative problem-solving techniques. Break mental patterns.',
      science: 'Divergent thinking, increases creative output by 60%',
      icon: 'BrainCircuit',
      color: 'rose',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'morning-pages',
      name: 'Artist\'s Way Morning Pages',
      category: 'creativity',
      level: 'Intermediate',
      duration: '30 min',
      description: 'Three pages of longhand morning writing. Unlock creative blocks.',
      science: 'Julia Cameron technique, accesses subconscious creativity',
      icon: 'PenTool',
      color: 'rose',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'flow-activities',
      name: 'Flow State Activities',
      category: 'creativity',
      level: 'Advanced',
      duration: 'Variable',
      description: 'Mihaly Csikszentmihalyi\'s flow triggers. Optimal challenge-skill balance.',
      science: 'Flow research, creativity and productivity increase 500%',
      icon: 'Flame',
      color: 'rose',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'mind-mapping',
      name: 'Mind Mapping',
      category: 'creativity',
      level: 'Beginner',
      duration: '15 min',
      description: 'Tony Buzan\'s visual brainstorming technique. Organize ideas radially.',
      science: 'Activates visual and verbal processing, enhances memory',
      icon: 'BrainCircuit',
      color: 'rose',
      isActive: true,
      usageCount: 0,
    },

    // Social Intelligence (5 tools)
    {
      toolId: 'active-listening',
      name: 'Active Listening Practice',
      category: 'social-intelligence',
      level: 'Beginner',
      duration: '15 min',
      description: 'Develop deep listening skills. Understand before being understood.',
      science: 'Empathic accuracy training, improves relationship satisfaction',
      icon: 'MessageCircle',
      color: 'indigo',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'conflict-resolution',
      name: 'Conflict Resolution Protocol',
      category: 'social-intelligence',
      level: 'Intermediate',
      duration: '20 min',
      description: 'Marshall Rosenberg\'s Nonviolent Communication. Resolve conflicts peacefully.',
      science: 'NVC increases empathy and reduces aggressive communication',
      icon: 'Shield',
      color: 'indigo',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'emotional-labelling',
      name: 'Emotion Labelling',
      category: 'social-intelligence',
      level: 'Beginner',
      duration: '5 min',
      description: 'Name emotions accurately to manage them better. Expand emotional vocabulary.',
      science: 'Affect labeling research, reduces amygdala activation by 30%',
      icon: 'Heart',
      color: 'indigo',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'perspective-taking',
      name: 'Perspective Taking',
      category: 'social-intelligence',
      level: 'Intermediate',
      duration: '10 min',
      description: 'Practice seeing situations from others\' viewpoints. Develop cognitive empathy.',
      science: 'Theory of mind exercises, increases empathy and reduces bias',
      icon: 'Eye',
      color: 'indigo',
      isActive: true,
      usageCount: 0,
    },
    {
      toolId: 'difficult-conversations',
      name: 'Difficult Conversations',
      category: 'social-intelligence',
      level: 'Advanced',
      duration: '25 min',
      description: 'Prepare for and navigate challenging discussions. Harvard negotiation techniques.',
      science: 'Reduces defensiveness, increases mutual understanding',
      icon: 'MessageCircle',
      color: 'indigo',
      isActive: true,
      usageCount: 0,
    },
  ];

  for (const tool of brainTools) {
    await brainToolRepo.save(brainToolRepo.create(tool));
  }

  // Seed Books (28 books with complete metadata)
  const books = [
    // Productivity & Habits
    {
      title: 'Atomic Habits',
      author: 'James Clear',
      category: 'Productivity',
      emoji: '⚛️',
      rating: 4.8,
      pages: 320,
      readTime: '5h 30m',
      description: 'Tiny changes, remarkable results. The definitive guide to building good habits and breaking bad ones. Learn the proven framework for improving every day.',
      keyInsights: JSON.stringify([
        'The 1% rule: Small improvements compound over time',
        'Focus on systems, not goals',
        'The Four Laws of Behavior Change',
        'Environment design is crucial for habit success',
      ]),
      tags: JSON.stringify(['habits', 'productivity', 'self-improvement', 'behavior-change']),
      isActive: true,
    },
    {
      title: 'Deep Work',
      author: 'Cal Newport',
      category: 'Productivity',
      emoji: '🎯',
      rating: 4.7,
      pages: 296,
      readTime: '5h 15m',
      description: 'Rules for focused success in a distracted world. Learn to perform at your cognitive peak and produce work that matters.',
      keyInsights: JSON.stringify([
        'Deep work is increasingly rare and valuable',
        'Busyness is not productivity',
        'Schedule every minute of your day',
        'Quit social media (or be selective)',
      ]),
      tags: JSON.stringify(['focus', 'productivity', 'concentration', 'career']),
      isActive: true,
    },
    {
      title: 'The Power of Habit',
      author: 'Charles Duhigg',
      category: 'Productivity',
      emoji: '🔄',
      rating: 4.6,
      pages: 371,
      readTime: '6h 45m',
      description: 'Why we do what we do in life and business. Understand the science of habits and learn to transform your life.',
      keyInsights: JSON.stringify([
        'The habit loop: Cue, Routine, Reward',
        'Keystone habits create chain reactions',
        'Willpower is the most important habit',
        'Small wins trigger transformative changes',
      ]),
      tags: JSON.stringify(['habits', 'neuroscience', 'behavior', 'psychology']),
      isActive: true,
    },
    {
      title: 'Getting Things Done',
      author: 'David Allen',
      category: 'Productivity',
      emoji: '✅',
      rating: 4.5,
      pages: 352,
      readTime: '6h 20m',
      description: 'The art of stress-free productivity. Master the complete system for organizing your work and life.',
      keyInsights: JSON.stringify([
        'Capture everything in a trusted system',
        'The two-minute rule for quick tasks',
        'Weekly review is essential',
        'Clear your mind to focus better',
      ]),
      tags: JSON.stringify(['productivity', 'organization', 'time-management', 'gtd']),
      isActive: true,
    },
    {
      title: 'Essentialism',
      author: 'Greg McKeown',
      category: 'Productivity',
      emoji: '🎯',
      rating: 4.7,
      pages: 272,
      readTime: '4h 50m',
      description: 'The disciplined pursuit of less. Learn to do less but better, saying no to nonessentials.',
      keyInsights: JSON.stringify([
        'Less but better: The core of essentialism',
        'Learn to say no gracefully',
        'Eliminate the trivial many',
        'Create space to think and explore',
      ]),
      tags: JSON.stringify(['minimalism', 'focus', 'priorities', 'decision-making']),
      isActive: true,
    },

    // Psychology & Thinking
    {
      title: 'Thinking, Fast and Slow',
      author: 'Daniel Kahneman',
      category: 'Psychology',
      emoji: '🧠',
      rating: 4.6,
      pages: 499,
      readTime: '9h 15m',
      description: 'Nobel Prize winner reveals the two systems that drive how we think. System 1 is fast and intuitive; System 2 is slow and deliberate.',
      keyInsights: JSON.stringify([
        'Two systems of thinking: Fast (intuitive) and Slow (deliberate)',
        'Cognitive biases affect all decisions',
        'Loss aversion is powerful',
        'We overestimate our understanding',
      ]),
      tags: JSON.stringify(['psychology', 'decision-making', 'cognitive-bias', 'behavioral-economics']),
      isActive: true,
    },
    {
      title: 'Predictably Irrational',
      author: 'Dan Ariely',
      category: 'Psychology',
      emoji: '🔮',
      rating: 4.5,
      pages: 384,
      readTime: '6h 50m',
      description: 'The hidden forces that shape our decisions. Discover why we make irrational choices consistently.',
      keyInsights: JSON.stringify([
        'We are predictably irrational',
        'The power of free and anchoring',
        'Social norms vs. market norms',
        'Context shapes all decisions',
      ]),
      tags: JSON.stringify(['behavioral-economics', 'psychology', 'decision-making', 'irrationality']),
      isActive: true,
    },
    {
      title: 'The Happiness Hypothesis',
      author: 'Jonathan Haidt',
      category: 'Psychology',
      emoji: '😊',
      rating: 4.6,
      pages: 320,
      readTime: '5h 40m',
      description: 'Finding modern truth in ancient wisdom. Explore happiness through the lens of philosophy and psychology.',
      keyInsights: JSON.stringify([
        'The mind is divided like a rider on an elephant',
        'Happiness comes from between, not within',
        'Love and work are the pillars of happiness',
        'We adapt to most circumstances',
      ]),
      tags: JSON.stringify(['happiness', 'psychology', 'philosophy', 'well-being']),
      isActive: true,
    },
    {
      title: 'Influence: The Psychology of Persuasion',
      author: 'Robert Cialdini',
      category: 'Psychology',
      emoji: '🎭',
      rating: 4.7,
      pages: 336,
      readTime: '6h 0m',
      description: 'The classic book on the science of influence. Learn the six universal principles of persuasion.',
      keyInsights: JSON.stringify([
        'Six principles: Reciprocity, commitment, social proof, authority, liking, scarcity',
        'Automatic compliance triggers',
        'How to defend against manipulation',
        'Ethical influence in action',
      ]),
      tags: JSON.stringify(['persuasion', 'influence', 'psychology', 'social-proof']),
      isActive: true,
    },

    // Mindfulness & Meditation
    {
      title: 'Wherever You Go, There You Are',
      author: 'Jon Kabat-Zinn',
      category: 'Mindfulness',
      emoji: '🧘',
      rating: 4.5,
      pages: 304,
      readTime: '5h 20m',
      description: 'Mindfulness meditation in everyday life. The classic guide to living in the present moment.',
      keyInsights: JSON.stringify([
        'Mindfulness is simple but not easy',
        'Present moment awareness is the practice',
        'Non-judging observation of experience',
        'Meditation is a way of being, not doing',
      ]),
      tags: JSON.stringify(['mindfulness', 'meditation', 'mbsr', 'presence']),
      isActive: true,
    },
    {
      title: '10% Happier',
      author: 'Dan Harris',
      category: 'Mindfulness',
      emoji: '📿',
      rating: 4.5,
      pages: 256,
      readTime: '4h 30m',
      description: 'How I tamed the voice in my head. A skeptic\'s journey to mindfulness without losing your edge.',
      keyInsights: JSON.stringify([
        'Meditation is not about being calm',
        'The voice in your head is not you',
        'Mindfulness is a superpower',
        'You can be ambitious and mindful',
      ]),
      tags: JSON.stringify(['meditation', 'mindfulness', 'self-improvement', 'anxiety']),
      isActive: true,
    },
    {
      title: 'The Miracle of Mindfulness',
      author: 'Thich Nhat Hanh',
      category: 'Mindfulness',
      emoji: '☸️',
      rating: 4.7,
      pages: 150,
      readTime: '2h 40m',
      description: 'An introduction to the practice of meditation. Simple practices from the master of mindfulness.',
      keyInsights: JSON.stringify([
        'Wash dishes to wash dishes',
        'Walking meditation practice',
        'Conscious breathing anchors presence',
        'Mindfulness in daily activities',
      ]),
      tags: JSON.stringify(['mindfulness', 'buddhism', 'meditation', 'zen']),
      isActive: true,
    },

    // Neuroscience & Health
    {
      title: 'Why We Sleep',
      author: 'Matthew Walker',
      category: 'Health',
      emoji: '😴',
      rating: 4.6,
      pages: 368,
      readTime: '6h 30m',
      description: 'Unlocking the power of sleep and dreams. The groundbreaking exploration of sleep science.',
      keyInsights: JSON.stringify([
        'Sleep is the single most effective health behavior',
        'Lack of sleep increases disease risk',
        'REM and deep sleep serve different functions',
        'Consistent sleep schedule is crucial',
      ]),
      tags: JSON.stringify(['sleep', 'neuroscience', 'health', 'performance']),
      isActive: true,
    },
    {
      title: 'The Brain That Changes Itself',
      author: 'Norman Doidge',
      category: 'Neuroscience',
      emoji: '🧬',
      rating: 4.6,
      pages: 427,
      readTime: '7h 45m',
      description: 'Stories of personal triumph from the frontiers of brain science. Neuroplasticity in action.',
      keyInsights: JSON.stringify([
        'The brain can rewire itself throughout life',
        'Use it or lose it principle',
        'Mental training changes brain structure',
        'Recovery from brain injury is possible',
      ]),
      tags: JSON.stringify(['neuroscience', 'neuroplasticity', 'brain', 'recovery']),
      isActive: true,
    },
    {
      title: 'Breath',
      author: 'James Nestor',
      category: 'Health',
      emoji: '🌬️',
      rating: 4.7,
      pages: 304,
      readTime: '5h 20m',
      description: 'The new science of a lost art. How breathing properly can transform your health.',
      keyInsights: JSON.stringify([
        'Nose breathing vs. mouth breathing',
        'Slow breathing activates parasympathetic system',
        'Ancient breathing techniques validated by science',
        'Breathing affects every system in the body',
      ]),
      tags: JSON.stringify(['breathing', 'health', 'wellness', 'respiration']),
      isActive: true,
    },

    // Flow & Performance
    {
      title: 'Flow',
      author: 'Mihaly Csikszentmihalyi',
      category: 'Performance',
      emoji: '🌊',
      rating: 4.6,
      pages: 303,
      readTime: '5h 30m',
      description: 'The psychology of optimal experience. The classic work on achieving peak performance and happiness.',
      keyInsights: JSON.stringify([
        'Flow is the secret to happiness',
        'Challenge-skill balance creates flow',
        'Clear goals and immediate feedback',
        'Loss of self-consciousness in flow',
      ]),
      tags: JSON.stringify(['flow', 'performance', 'psychology', 'happiness']),
      isActive: true,
    },
    {
      title: 'Peak Performance',
      author: 'Brad Stulberg & Steve Magness',
      category: 'Performance',
      emoji: '🏔️',
      rating: 4.6,
      pages: 256,
      readTime: '4h 30m',
      description: 'Elevate your game, avoid burnout. Science-backed strategies from elite performers.',
      keyInsights: JSON.stringify([
        'Stress + Rest = Growth',
        'Purpose fuels performance',
        'Minimize distractions',
        'Build routines, not habits',
      ]),
      tags: JSON.stringify(['performance', 'athletics', 'burnout', 'growth']),
      isActive: true,
    },
    {
      title: 'The Rise of Superman',
      author: 'Steven Kotler',
      category: 'Performance',
      emoji: '🦸',
      rating: 4.5,
      pages: 234,
      readTime: '4h 10m',
      description: 'Decoding the science of ultimate human performance. How flow states enable impossible feats.',
      keyInsights: JSON.stringify([
        'Flow triggers in extreme sports',
        'Group flow amplifies individual flow',
        'Flow hacking techniques',
        'The neuroscience of impossible',
      ]),
      tags: JSON.stringify(['flow', 'extreme-sports', 'performance', 'neuroscience']),
      isActive: true,
    },

    // Emotional Intelligence
    {
      title: 'Emotional Intelligence',
      author: 'Daniel Goleman',
      category: 'Psychology',
      emoji: '❤️',
      rating: 4.5,
      pages: 384,
      readTime: '6h 50m',
      description: 'Why it can matter more than IQ. The groundbreaking book on understanding emotions.',
      keyInsights: JSON.stringify([
        'EQ predicts success better than IQ',
        'Five components of emotional intelligence',
        'Emotional literacy is learnable',
        'Self-awareness is the foundation',
      ]),
      tags: JSON.stringify(['emotional-intelligence', 'psychology', 'relationships', 'success']),
      isActive: true,
    },
    {
      title: 'Nonviolent Communication',
      author: 'Marshall Rosenberg',
      category: 'Communication',
      emoji: '🕊️',
      rating: 4.7,
      pages: 220,
      readTime: '3h 55m',
      description: 'A language of life. Transform conflicts through compassionate communication.',
      keyInsights: JSON.stringify([
        'Four components: observations, feelings, needs, requests',
        'Empathy before solutions',
        'All actions are attempts to meet needs',
        'Receiving empathically',
      ]),
      tags: JSON.stringify(['communication', 'empathy', 'conflict-resolution', 'relationships']),
      isActive: true,
    },

    // Self-Compassion & Resilience
    {
      title: 'Self-Compassion',
      author: 'Kristin Neff',
      category: 'Wellness',
      emoji: '🤗',
      rating: 4.6,
      pages: 320,
      readTime: '5h 40m',
      description: 'The proven power of being kind to yourself. Stop beating yourself up and leave insecurity behind.',
      keyInsights: JSON.stringify([
        'Three components: self-kindness, common humanity, mindfulness',
        'Self-compassion increases motivation',
        'Reduces depression and anxiety',
        'Practice self-compassion breaks',
      ]),
      tags: JSON.stringify(['self-compassion', 'mindfulness', 'mental-health', 'kindness']),
      isActive: true,
    },
    {
      title: 'The Gifts of Imperfection',
      author: 'Brené Brown',
      category: 'Wellness',
      emoji: '💝',
      rating: 4.7,
      pages: 137,
      readTime: '2h 25m',
      description: 'Let go of who you think you\'re supposed to be and embrace who you are. Guideposts for wholehearted living.',
      keyInsights: JSON.stringify([
        'Courage, compassion, connection',
        'Vulnerability is strength',
        'Shame resilience practices',
        'Cultivate gratitude and joy',
      ]),
      tags: JSON.stringify(['vulnerability', 'authenticity', 'shame', 'wholehearted-living']),
      isActive: true,
    },
    {
      title: 'Man\'s Search for Meaning',
      author: 'Viktor Frankl',
      category: 'Philosophy',
      emoji: '🎯',
      rating: 4.8,
      pages: 165,
      readTime: '2h 55m',
      description: 'A Holocaust survivor\'s account of finding meaning in suffering. The foundational text of logotherapy.',
      keyInsights: JSON.stringify([
        'Meaning can be found in any situation',
        'Suffering ceases to be suffering when it finds meaning',
        'Freedom to choose your attitude',
        'Life is never without meaning',
      ]),
      tags: JSON.stringify(['meaning', 'philosophy', 'resilience', 'existentialism']),
      isActive: true,
    },

    // Creativity & Learning
    {
      title: 'The War of Art',
      author: 'Steven Pressfield',
      category: 'Creativity',
      emoji: '⚔️',
      rating: 4.6,
      pages: 190,
      readTime: '3h 20m',
      description: 'Break through the blocks and win your inner creative battles. Resistance is the enemy.',
      keyInsights: JSON.stringify([
        'Resistance is the enemy of creativity',
        'Turn pro: show up every day',
        'Inspiration follows action',
        'Overcome perfectionism and fear',
      ]),
      tags: JSON.stringify(['creativity', 'resistance', 'art', 'procrastination']),
      isActive: true,
    },
    {
      title: 'A Mind for Numbers',
      author: 'Barbara Oakley',
      category: 'Learning',
      emoji: '🔢',
      rating: 4.6,
      pages: 336,
      readTime: '6h 0m',
      description: 'How to excel at math and science. Learn how to learn using neuroscience insights.',
      keyInsights: JSON.stringify([
        'Focused and diffuse thinking modes',
        'The Pomodoro Technique for learning',
        'Chunking information',
        'Spaced repetition and recall',
      ]),
      tags: JSON.stringify(['learning', 'math', 'science', 'education']),
      isActive: true,
    },
    {
      title: 'Range',
      author: 'David Epstein',
      category: 'Learning',
      emoji: '🎯',
      rating: 4.5,
      pages: 352,
      readTime: '6h 20m',
      description: 'Why generalists triumph in a specialized world. The case for broad experience.',
      keyInsights: JSON.stringify([
        'Sampling period before specializing',
        'Lateral thinking from diverse experience',
        'Match quality: find the right fit',
        'Slow learning is better learning',
      ]),
      tags: JSON.stringify(['learning', 'generalist', 'expertise', 'education']),
      isActive: true,
    },

    // Relationships & Connection
    {
      title: 'Attached',
      author: 'Amir Levine & Rachel Heller',
      category: 'Relationships',
      emoji: '💞',
      rating: 4.5,
      pages: 304,
      readTime: '5h 20m',
      description: 'The new science of adult attachment. Understand your attachment style and find the right partner.',
      keyInsights: JSON.stringify([
        'Three attachment styles: secure, anxious, avoidant',
        'Attachment theory in adult relationships',
        'How to become more secure',
        'Compatibility through attachment',
      ]),
      tags: JSON.stringify(['relationships', 'attachment', 'love', 'psychology']),
      isActive: true,
    },
    {
      title: 'The Five Love Languages',
      author: 'Gary Chapman',
      category: 'Relationships',
      emoji: '❤️',
      rating: 4.7,
      pages: 203,
      readTime: '3h 35m',
      description: 'The secret to love that lasts. Discover how you and your partner express love differently.',
      keyInsights: JSON.stringify([
        'Five languages: words, acts, gifts, time, touch',
        'Speak your partner\'s language',
        'Love tank concept',
        'Maintaining love requires effort',
      ]),
      tags: JSON.stringify(['relationships', 'love', 'communication', 'marriage']),
      isActive: true,
    },
  ];

  for (const book of books) {
    await bookRepo.save(bookRepo.create(book));
  }

  // Seed Templates (15 comprehensive templates)
  const templates = [
    // Professional Templates
    {
      title: 'Ultimate Habit Tracker Dashboard',
      category: 'Professional',
      description: 'Comprehensive habit tracking system with advanced analytics, streak tracking, and goal visualization. Includes daily, weekly, and monthly views.',
      format: 'Notion',
      downloadUrl: '/templates/habit-tracker-pro.zip',
      downloadCount: 3247,
      features: JSON.stringify(['Daily habit checkboxes', 'Streak counter & badges', 'Progress analytics & charts', 'Goal setting wizard', 'Habit stacking templates', 'Monthly review prompts']),
      isActive: true,
    },
    {
      title: 'Project Management System',
      category: 'Professional',
      description: 'Complete project management solution with kanban boards, timeline views, and resource allocation. Perfect for teams or solo entrepreneurs.',
      format: 'Notion',
      downloadUrl: '/templates/project-management.zip',
      downloadCount: 2891,
      features: JSON.stringify(['Kanban board', 'Gantt chart view', 'Resource allocation', 'Client database', 'Meeting notes', 'Invoice tracker']),
      isActive: true,
    },
    {
      title: 'Content Creator Dashboard',
      category: 'Professional',
      description: 'All-in-one system for content creators. Plan, create, schedule, and analyze your content across all platforms.',
      format: 'Notion',
      downloadUrl: '/templates/content-creator.zip',
      downloadCount: 4512,
      features: JSON.stringify(['Content calendar', 'Idea vault', 'Analytics dashboard', 'Brand guidelines', 'Collaboration tools', 'Publishing checklist']),
      isActive: true,
    },
    {
      title: 'Meeting Notes & Action Items',
      category: 'Professional',
      description: 'Streamlined meeting documentation with action item tracking, decision logging, and follow-up reminders.',
      format: 'Google Docs',
      downloadUrl: '/templates/meeting-notes.gdoc',
      downloadCount: 1823,
      features: JSON.stringify(['Agenda templates', 'Action item tracker', 'Decision log', 'Attendee list', 'Follow-up automation', 'Archive system']),
      isActive: true,
    },

    // Student Templates
    {
      title: 'Student Life Planner',
      category: 'Student',
      description: 'Complete academic organization system. Track classes, assignments, exams, and extracurriculars all in one place.',
      format: 'Notion',
      downloadUrl: '/templates/student-planner.zip',
      downloadCount: 5634,
      features: JSON.stringify(['Class schedule', 'Assignment tracker', 'Exam calendar', 'Grade calculator', 'Study timer', 'Resource library']),
      isActive: true,
    },
    {
      title: 'Research Paper Organizer',
      category: 'Student',
      description: 'Systematic approach to academic research. Organize sources, notes, outlines, and drafts efficiently.',
      format: 'Notion',
      downloadUrl: '/templates/research-organizer.zip',
      downloadCount: 2145,
      features: JSON.stringify(['Source database', 'Citation manager', 'Note-taking system', 'Outline builder', 'Draft versions', 'Bibliography generator']),
      isActive: true,
    },

    // Personal Templates
    {
      title: 'Weekly Planning Template',
      category: 'Personal',
      description: 'Plan your perfect week with time-blocking, priorities, and reflection prompts. Achieve work-life balance.',
      format: 'Notion',
      downloadUrl: '/templates/weekly-planner.zip',
      downloadCount: 4892,
      features: JSON.stringify(['Time-block calendar', 'Priority matrix', 'Energy management', 'Weekly review', 'Gratitude journal', 'Goal tracking']),
      isActive: true,
    },
    {
      title: 'Personal Finance Tracker',
      category: 'Personal',
      description: 'Complete personal finance system. Track income, expenses, investments, and achieve your financial goals.',
      format: 'Excel',
      downloadUrl: '/templates/finance-tracker.xlsx',
      downloadCount: 6103,
      features: JSON.stringify(['Income tracking', 'Expense categories', 'Budget planning', 'Savings goals', 'Investment dashboard', 'Net worth calculator', 'Bill reminders']),
      isActive: true,
    },
    {
      title: 'Fitness & Nutrition Journal',
      category: 'Personal',
      description: 'Track workouts, meals, and progress toward your health goals. Includes exercise library and meal planning.',
      format: 'Notion',
      downloadUrl: '/templates/fitness-journal.zip',
      downloadCount: 3789,
      features: JSON.stringify(['Workout logger', 'Meal planner', 'Progress photos', 'Measurements tracker', 'Exercise library', 'Recipe database']),
      isActive: true,
    },
    {
      title: 'Travel Planning System',
      category: 'Personal',
      description: 'Plan your dream trips with itinerary builder, packing lists, budget tracker, and travel journal.',
      format: 'Notion',
      downloadUrl: '/templates/travel-planner.zip',
      downloadCount: 2567,
      features: JSON.stringify(['Itinerary builder', 'Packing checklists', 'Budget tracker', 'Booking confirmations', 'Travel journal', 'Photo albums']),
      isActive: true,
    },

    // Creative Templates
    {
      title: 'Writer\'s Workspace',
      category: 'Creative',
      description: 'Complete writing environment for novelists, bloggers, and storytellers. Organize characters, plots, and drafts.',
      format: 'Notion',
      downloadUrl: '/templates/writers-workspace.zip',
      downloadCount: 3412,
      features: JSON.stringify(['Story outline', 'Character profiles', 'World-building', 'Chapter tracker', 'Writing prompts', 'Publishing checklist']),
      isActive: true,
    },
    {
      title: 'Creative Portfolio System',
      category: 'Creative',
      description: 'Showcase your creative work professionally. Perfect for designers, photographers, and artists.',
      format: 'Notion',
      downloadUrl: '/templates/portfolio.zip',
      downloadCount: 2876,
      features: JSON.stringify(['Project gallery', 'Client testimonials', 'Case studies', 'Bio & about', 'Contact form', 'Service packages']),
      isActive: true,
    },

    // Wellness Templates
    {
      title: 'Mental Health Journal',
      category: 'Personal',
      description: 'Daily mental health tracking with mood logging, CBT exercises, and gratitude practice. Based on clinical psychology.',
      format: 'Notion',
      downloadUrl: '/templates/mental-health-journal.zip',
      downloadCount: 4234,
      features: JSON.stringify(['Mood tracker', 'CBT thought records', 'Gratitude log', 'Self-care checklist', 'Therapist notes', 'Crisis resources']),
      isActive: true,
    },
    {
      title: 'Morning & Evening Routine',
      category: 'Personal',
      description: 'Build powerful daily routines that stick. Science-backed templates for morning and evening rituals.',
      format: 'PDF',
      downloadUrl: '/templates/daily-routines.pdf',
      downloadCount: 5123,
      features: JSON.stringify(['Morning routine', 'Evening routine', 'Habit stacking', 'Time estimates', 'Customizable blocks', 'Progress tracking']),
      isActive: true,
    },

    // Business Templates
    {
      title: 'Business Plan Template',
      category: 'Professional',
      description: 'Comprehensive business planning system. From idea validation to financial projections and marketing strategy.',
      format: 'Notion',
      downloadUrl: '/templates/business-plan.zip',
      downloadCount: 1945,
      features: JSON.stringify(['Executive summary', 'Market analysis', 'Financial projections', 'Marketing strategy', 'Operations plan', 'Pitch deck']),
      isActive: true,
    },
  ];

  for (const template of templates) {
    await templateRepo.save(templateRepo.create(template));
  }

  // Seed Media (30 audio/video items with complete metadata)
  const media = [
    // Focus Audio (5 tracks)
    {
      mediaType: 'audio' as const,
      title: 'Deep Focus Binaural Beats - 40Hz Gamma',
      category: 'Focus',
      description: '40Hz gamma wave binaural beats designed for maximum concentration. Used by neuroscientists and productivity experts. Pure tones with no music distractions.',
      mediaUrl: '/media/audio/focus-gamma-40hz.mp3',
      duration: '60 min',
      playCount: 8421,
      rating: 4.8,
      tags: JSON.stringify(['binaural', 'gamma', 'focus', 'concentration', 'study']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Lo-Fi Study Beats - Chill Instrumentals',
      category: 'Focus',
      description: 'Relaxing lo-fi hip hop beats for studying and working. Non-distracting instrumental music that enhances focus without overwhelming.',
      mediaUrl: '/media/audio/lofi-study-beats.mp3',
      duration: '90 min',
      instructor: 'ChilledCow',
      playCount: 15234,
      rating: 4.9,
      tags: JSON.stringify(['lofi', 'study', 'instrumental', 'chill', 'beats']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Classical Music for Concentration - Mozart Effect',
      category: 'Focus',
      description: 'Carefully selected classical compositions known to enhance cognitive performance. The Mozart effect in action.',
      mediaUrl: '/media/audio/classical-focus.mp3',
      duration: '120 min',
      instructor: 'Various Classical Composers',
      playCount: 6789,
      rating: 4.7,
      tags: JSON.stringify(['classical', 'mozart', 'focus', 'cognitive', 'music']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'White Noise - Pure Focus Environment',
      category: 'Focus',
      description: 'High-quality white noise to mask distracting sounds. Perfect for open offices or noisy environments.',
      mediaUrl: '/media/audio/white-noise.mp3',
      duration: '180 min',
      playCount: 4523,
      rating: 4.6,
      tags: JSON.stringify(['white-noise', 'ambiance', 'focus', 'concentration', 'masking']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Forest Sounds - Natural Productivity Boost',
      category: 'Focus',
      description: 'Immersive forest ambiance with birdsong and rustling leaves. Nature sounds proven to reduce stress and improve focus.',
      mediaUrl: '/media/audio/forest-ambiance.mp3',
      duration: '45 min',
      playCount: 9876,
      rating: 4.8,
      tags: JSON.stringify(['nature', 'forest', 'ambiance', 'stress-relief', 'natural']),
      isActive: true,
    },

    // Relaxation Audio (5 tracks)
    {
      mediaType: 'audio' as const,
      title: 'Progressive Muscle Relaxation - Full Body',
      category: 'Relaxation',
      description: 'Guided progressive muscle relaxation (PMR) for deep stress relief. Systematic tension and release through all muscle groups.',
      mediaUrl: '/media/audio/pmr-full-body.mp3',
      duration: '25 min',
      instructor: 'Dr. Sarah Johnson',
      playCount: 7234,
      rating: 4.9,
      tags: JSON.stringify(['pmr', 'relaxation', 'stress-relief', 'muscle-tension', 'guided']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Ocean Waves - Coastal Relaxation',
      category: 'Relaxation',
      description: 'High-fidelity ocean wave sounds recorded on pristine beaches. Natural relaxation and stress reduction.',
      mediaUrl: '/media/audio/ocean-waves.mp3',
      duration: '60 min',
      playCount: 12456,
      rating: 4.8,
      tags: JSON.stringify(['ocean', 'waves', 'nature', 'relaxation', 'coastal']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Tibetan Singing Bowls - Sound Healing',
      category: 'Relaxation',
      description: 'Authentic Tibetan singing bowl ceremony recorded in the Himalayas. Ancient sound healing for modern stress.',
      mediaUrl: '/media/audio/singing-bowls.mp3',
      duration: '30 min',
      instructor: 'Master Tenzin',
      playCount: 5678,
      rating: 4.7,
      tags: JSON.stringify(['tibetan', 'singing-bowls', 'sound-healing', 'ancient', 'meditation']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Rain & Thunder - Cozy Ambiance',
      category: 'Relaxation',
      description: 'Gentle rain with distant thunder. Perfect for relaxation, reading, or creating cozy atmosphere.',
      mediaUrl: '/media/audio/rain-thunder.mp3',
      duration: '90 min',
      playCount: 14532,
      rating: 4.9,
      tags: JSON.stringify(['rain', 'thunder', 'ambiance', 'cozy', 'relaxation']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Guided Body Scan - MBSR Practice',
      category: 'Relaxation',
      description: 'Mindfulness-based stress reduction (MBSR) body scan meditation. Systematic awareness practice from Jon Kabat-Zinn\'s program.',
      mediaUrl: '/media/audio/mbsr-body-scan.mp3',
      duration: '45 min',
      instructor: 'Dr. Jon Kabat-Zinn',
      playCount: 6789,
      rating: 4.9,
      tags: JSON.stringify(['mbsr', 'body-scan', 'mindfulness', 'meditation', 'stress-reduction']),
      isActive: true,
    },

    // Sleep Audio (5 tracks)
    {
      mediaType: 'audio' as const,
      title: 'Deep Sleep Meditation - Fall Asleep Fast',
      category: 'Sleep',
      description: 'Guided sleep meditation with progressive relaxation and visualization. Designed to help you fall asleep within 20 minutes.',
      mediaUrl: '/media/audio/sleep-meditation.mp3',
      duration: '45 min',
      instructor: 'Dr. Sarah Johnson',
      playCount: 25234,
      rating: 4.9,
      tags: JSON.stringify(['sleep', 'meditation', 'insomnia', 'relaxation', 'bedtime']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Delta Wave Sleep Music - 0.5-4Hz',
      category: 'Sleep',
      description: 'Delta wave binaural beats for deep, restorative sleep. Scientifically designed to entrain your brain to sleep frequencies.',
      mediaUrl: '/media/audio/delta-sleep.mp3',
      duration: '480 min',
      playCount: 18765,
      rating: 4.8,
      tags: JSON.stringify(['delta-waves', 'deep-sleep', 'binaural', 'restorative', 'long']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Sleep Hypnosis - Powerful Insomnia Relief',
      category: 'Sleep',
      description: 'Clinical hypnotherapy session for chronic insomnia. Uses proven techniques to reprogram sleep patterns.',
      mediaUrl: '/media/audio/sleep-hypnosis.mp3',
      duration: '60 min',
      instructor: 'Michael Sealey',
      playCount: 34521,
      rating: 4.9,
      tags: JSON.stringify(['hypnosis', 'insomnia', 'sleep', 'clinical', 'therapy']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Bedtime Stories for Adults - The Sleepy Forest',
      category: 'Sleep',
      description: 'Calming bedtime story narrated in a soothing voice. Perfect for shutting down an overactive mind.',
      mediaUrl: '/media/audio/bedtime-story.mp3',
      duration: '35 min',
      instructor: 'Stephen Fry',
      playCount: 19876,
      rating: 4.8,
      tags: JSON.stringify(['bedtime-story', 'sleep', 'narration', 'calming', 'adults']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Brown Noise - Deep Sleep Enhancement',
      category: 'Sleep',
      description: 'Pure brown noise for the deepest sleep. Lower frequency than white noise, more effective for sleeping.',
      mediaUrl: '/media/audio/brown-noise-sleep.mp3',
      duration: '600 min',
      playCount: 11234,
      rating: 4.7,
      tags: JSON.stringify(['brown-noise', 'deep-sleep', 'noise-masking', 'restful', 'long']),
      isActive: true,
    },

    // Meditation Audio (5 tracks)
    {
      mediaType: 'audio' as const,
      title: 'Mindfulness Meditation - Beginner Friendly',
      category: 'Meditation',
      description: 'Introduction to mindfulness meditation. Learn to observe your thoughts without judgment. Perfect for beginners.',
      mediaUrl: '/media/audio/mindfulness-beginner.mp3',
      duration: '10 min',
      instructor: 'Tara Brach',
      playCount: 16789,
      rating: 4.8,
      tags: JSON.stringify(['mindfulness', 'beginner', 'meditation', 'awareness', 'simple']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Loving Kindness Meditation - Metta Practice',
      category: 'Meditation',
      description: 'Traditional Buddhist metta meditation. Cultivate compassion for yourself and others through guided phrases.',
      mediaUrl: '/media/audio/loving-kindness.mp3',
      duration: '20 min',
      instructor: 'Sharon Salzberg',
      playCount: 8234,
      rating: 4.9,
      tags: JSON.stringify(['metta', 'loving-kindness', 'compassion', 'buddhist', 'heart']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Vipassana Meditation - Insight Practice',
      category: 'Meditation',
      description: 'Traditional insight meditation technique. Observe sensations and develop deep wisdom through direct experience.',
      mediaUrl: '/media/audio/vipassana-practice.mp3',
      duration: '45 min',
      instructor: 'S.N. Goenka',
      playCount: 5432,
      rating: 4.7,
      tags: JSON.stringify(['vipassana', 'insight', 'buddhism', 'mindfulness', 'advanced']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Chakra Meditation - Energy Healing',
      category: 'Meditation',
      description: 'Journey through your seven chakras with visualization and affirmations. Balance your energy centers.',
      mediaUrl: '/media/audio/chakra-meditation.mp3',
      duration: '35 min',
      instructor: 'Deepak Chopra',
      playCount: 9876,
      rating: 4.6,
      tags: JSON.stringify(['chakra', 'energy', 'healing', 'visualization', 'spiritual']),
      isActive: true,
    },
    {
      mediaType: 'audio' as const,
      title: 'Zen Meditation - Zazen Practice',
      category: 'Meditation',
      description: 'Traditional Zen sitting meditation. Simple instructions for proper posture and breath awareness.',
      mediaUrl: '/media/audio/zen-zazen.mp3',
      duration: '30 min',
      instructor: 'Thich Nhat Hanh',
      playCount: 7123,
      rating: 4.8,
      tags: JSON.stringify(['zen', 'zazen', 'sitting', 'buddhism', 'traditional']),
      isActive: true,
    },

    // Wellness Videos (5 videos)
    {
      mediaType: 'video' as const,
      title: 'Morning Yoga Flow - Energizing Sequence',
      category: 'Wellness',
      description: 'Gentle yet energizing yoga sequence to wake up your body. Perfect morning routine for all levels.',
      mediaUrl: '/media/video/morning-yoga-flow.mp4',
      duration: '20 min',
      instructor: 'Adriene Mishler',
      viewCount: 34521,
      rating: 4.9,
      tags: JSON.stringify(['yoga', 'morning', 'flow', 'energy', 'gentle']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Yin Yoga for Deep Release - Evening Practice',
      category: 'Wellness',
      description: 'Slow-paced yin yoga targeting connective tissue. Perfect for evening relaxation and flexibility.',
      mediaUrl: '/media/video/yin-yoga-evening.mp4',
      duration: '45 min',
      instructor: 'Bernie Clark',
      viewCount: 18765,
      rating: 4.8,
      tags: JSON.stringify(['yin-yoga', 'evening', 'relaxation', 'flexibility', 'deep-stretch']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Tai Chi for Beginners - Complete Foundation',
      category: 'Wellness',
      description: 'Learn the fundamentals of Tai Chi. Moving meditation for balance, stress relief, and longevity.',
      mediaUrl: '/media/video/tai-chi-basics.mp4',
      duration: '30 min',
      instructor: 'Master Yang',
      viewCount: 12456,
      rating: 4.7,
      tags: JSON.stringify(['tai-chi', 'beginner', 'meditation', 'balance', 'martial-arts']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Desk Stretches - Office Wellness Routine',
      category: 'Wellness',
      description: 'Quick stretches you can do at your desk. Combat sitting fatigue and improve posture throughout the workday.',
      mediaUrl: '/media/video/desk-stretches.mp4',
      duration: '10 min',
      instructor: 'Dr. Kelly Starrett',
      viewCount: 23456,
      rating: 4.8,
      tags: JSON.stringify(['desk-stretches', 'office', 'posture', 'quick', 'work']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Mobility Flow - Full Body Maintenance',
      category: 'Wellness',
      description: 'Comprehensive mobility routine for joint health and movement quality. Essential for athletes and desk workers alike.',
      mediaUrl: '/media/video/mobility-flow.mp4',
      duration: '25 min',
      instructor: 'Ido Portal',
      viewCount: 15789,
      rating: 4.9,
      tags: JSON.stringify(['mobility', 'joint-health', 'movement', 'flexibility', 'athletic']),
      isActive: true,
    },

    // Breathwork Videos (5 videos)
    {
      mediaType: 'video' as const,
      title: 'Wim Hof Method - Complete Tutorial',
      category: 'Breathwork',
      description: 'Learn the famous Wim Hof breathing technique. Three rounds of controlled hyperventilation and breath retention.',
      mediaUrl: '/media/video/wim-hof-method.mp4',
      duration: '15 min',
      instructor: 'Wim Hof',
      viewCount: 45678,
      rating: 4.9,
      tags: JSON.stringify(['wim-hof', 'breathwork', 'cold-exposure', 'energy', 'advanced']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Box Breathing - Navy SEAL Technique',
      category: 'Breathwork',
      description: 'Master the box breathing technique used by Navy SEALs for stress management. Visual guidance for perfect timing.',
      mediaUrl: '/media/video/box-breathing.mp4',
      duration: '5 min',
      instructor: 'Mark Divine',
      viewCount: 28934,
      rating: 4.8,
      tags: JSON.stringify(['box-breathing', 'navy-seal', 'stress', 'tactical', 'simple']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Pranayama Masterclass - Yogic Breathing',
      category: 'Breathwork',
      description: 'Comprehensive guide to classical pranayama techniques. Nadi Shodhana, Kapalabhati, Ujjayi, and Bhramari.',
      mediaUrl: '/media/video/pranayama-masterclass.mp4',
      duration: '60 min',
      instructor: 'B.K.S. Iyengar',
      viewCount: 16789,
      rating: 4.9,
      tags: JSON.stringify(['pranayama', 'yogic', 'breathing', 'classical', 'comprehensive']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Breath for Anxiety Relief - Instant Calm',
      category: 'Breathwork',
      description: 'Quick breathing techniques for immediate anxiety reduction. 4-7-8 breath and other calming methods.',
      mediaUrl: '/media/video/anxiety-breath.mp4',
      duration: '8 min',
      instructor: 'Dr. Andrew Weil',
      viewCount: 38765,
      rating: 4.9,
      tags: JSON.stringify(['anxiety', 'calm', 'stress-relief', 'quick', 'therapeutic']),
      isActive: true,
    },
    {
      mediaType: 'video' as const,
      title: 'Holotropic Breathwork - Deep Healing Session',
      category: 'Breathwork',
      description: 'Powerful holotropic breathwork practice for emotional release and altered states. With safety guidelines.',
      mediaUrl: '/media/video/holotropic-breathwork.mp4',
      duration: '90 min',
      instructor: 'Stanislav Grof',
      viewCount: 9876,
      rating: 4.7,
      tags: JSON.stringify(['holotropic', 'healing', 'emotional-release', 'advanced', 'therapeutic']),
      isActive: true,
    },
  ];

  for (const item of media) {
    await mediaRepo.save(mediaRepo.create(item));
  }

  // Seed Courses (12 comprehensive courses)
  const courses = [
    {
      title: 'The Science of Well-Being',
      description: 'Yale\'s most popular course. Learn the science of happiness and build habits that stick. Evidence-based strategies for a better life.',
      category: 'Psychology',
      instructor: 'Prof. Laurie Santos',
      image: '/courses/wellbeing-yale.jpg',
      overview: 'Discover the surprising insights from psychology about what makes us happy. Learn practical strategies to build happiness into your daily life. This course combines cutting-edge research with practical applications. You\'ll understand why our expectations about happiness are often wrong, and how to overcome these misconceptions. Includes weekly challenges to build lasting habits.',
      notes: 'Weekly homework assignments, peer discussions, and a final project where you apply happiness principles to your life.',
      totalLessons: 10,
    },
    {
      title: 'Mindfulness-Based Stress Reduction (MBSR)',
      description: 'Complete 8-week MBSR program. Learn meditation and mindfulness practices to reduce stress and improve well-being.',
      category: 'Mindfulness',
      instructor: 'Jon Kabat-Zinn',
      image: '/courses/mbsr.jpg',
      overview: 'The original MBSR program developed at UMass Medical School. Proven to reduce stress, anxiety, and chronic pain. Learn body scan meditation, sitting meditation, mindful yoga, and walking meditation. Understand the neuroscience behind mindfulness. Each week builds on the last, culminating in a day-long retreat experience.',
      notes: 'Requires 45 minutes daily practice. Includes guided meditation audio, practice logs, and weekly group discussions.',
      totalLessons: 8,
    },
    {
      title: 'Cognitive Behavioral Therapy Skills',
      description: 'Master evidence-based CBT techniques to manage anxiety, depression, and negative thinking. Clinical psychology tools for everyday life.',
      category: 'Mental Health',
      instructor: 'Dr. David Burns',
      image: '/courses/cbt-skills.jpg',
      overview: 'Learn the gold standard of psychotherapy. Identify and challenge cognitive distortions, use thought records effectively, and apply behavioral activation. Understand the CBT model and how thoughts, feelings, and behaviors interact. Includes practical exercises for common issues like anxiety, depression, and anger management.',
      notes: 'Weekly thought record homework, self-assessment quizzes, and downloadable worksheets.',
      totalLessons: 12,
    },
    {
      title: 'Deep Work Mastery',
      description: 'Master focused work in a distracted world. Build systems for concentration, eliminate shallow work, and produce exceptional results.',
      category: 'Productivity',
      instructor: 'Cal Newport',
      image: '/courses/deep-work.jpg',
      overview: 'Transform your ability to focus. Learn the philosophies of deep work, create rituals that support concentration, and build your capacity for sustained focus. Understand attention restoration theory, implement time-blocking, and design your ideal workspace. Practical strategies for knowledge workers, students, and creatives.',
      notes: 'Includes productivity audit, deep work scheduling templates, and weekly focus challenges.',
      totalLessons: 6,
    },
    {
      title: 'The Habit Blueprint',
      description: 'Build atomic habits that compound over time. Scientific approach to behavior change based on James Clear\'s framework.',
      category: 'Habits',
      instructor: 'James Clear',
      image: '/courses/habit-blueprint.jpg',
      overview: 'Master the Four Laws of Behavior Change. Learn to make good habits obvious, attractive, easy, and satisfying. Understand habit stacking, environment design, and the power of identity-based habits. Break bad habits by inverting the laws. Includes case studies of habit transformation.',
      notes: 'Habit tracker templates, environment design worksheets, and 30-day challenge.',
      totalLessons: 8,
    },
    {
      title: 'Sleep Science & Optimization',
      description: 'Master the neuroscience of sleep. Learn to optimize your sleep for health, performance, and longevity based on Matthew Walker\'s research.',
      category: 'Health',
      instructor: 'Dr. Matthew Walker',
      image: '/courses/sleep-science.jpg',
      overview: 'Understand why we sleep and what happens when we don\'t get enough. Learn the stages of sleep, circadian rhythms, and sleep pressure. Discover evidence-based strategies to improve sleep quality. Understand the impacts of caffeine, alcohol, and technology. Create your personalized sleep protocol.',
      notes: 'Sleep diary templates, environment optimization checklist, and sleep hygiene protocols.',
      totalLessons: 10,
    },
    {
      title: 'Breathwork Fundamentals',
      description: 'Master breathing techniques from ancient traditions and modern science. Transform your nervous system, energy, and mental clarity.',
      category: 'Wellness',
      instructor: 'James Nestor & Wim Hof',
      image: '/courses/breathwork.jpg',
      overview: 'Explore the lost art of breathing. Learn nasal breathing, box breathing, Wim Hof method, pranayama techniques, and more. Understand the science of CO2 tolerance, oxygen efficiency, and breath holds. Apply breathing for stress relief, energy, focus, and sleep.',
      notes: 'Video demonstrations, practice schedules, and safety guidelines for advanced techniques.',
      totalLessons: 7,
    },
    {
      title: 'Flow State Training',
      description: 'Enter flow states on demand. Learn the neuroscience and psychology of optimal experience from Steven Kotler and Mihaly Csikszentmihalyi.',
      category: 'Performance',
      instructor: 'Steven Kotler',
      image: '/courses/flow-training.jpg',
      overview: 'Understand the 17 flow triggers. Learn to create conditions for flow in work, sports, and creative pursuits. Explore group flow dynamics. Master the challenge-skill balance. Understand flow blockers and how to overcome them. Study flow in extreme athletes, artists, and top performers.',
      notes: 'Flow trigger worksheets, challenge-skill assessments, and flow state journals.',
      totalLessons: 9,
    },
    {
      title: 'Emotional Intelligence Mastery',
      description: 'Develop your emotional intelligence. Self-awareness, self-regulation, motivation, empathy, and social skills based on Daniel Goleman\'s framework.',
      category: 'Psychology',
      instructor: 'Daniel Goleman',
      image: '/courses/eq-mastery.jpg',
      overview: 'Build the five pillars of emotional intelligence. Learn to recognize and manage your emotions. Understand others\' emotional states. Develop empathy and social awareness. Apply EQ in leadership, relationships, and conflict resolution. Includes self-assessment tools and practice scenarios.',
      notes: 'EQ assessment tests, journaling prompts, and interpersonal practice exercises.',
      totalLessons: 10,
    },
    {
      title: 'Nonviolent Communication',
      description: 'Transform conflicts through compassionate communication. Learn Marshall Rosenberg\'s powerful framework for connection and understanding.',
      category: 'Communication',
      instructor: 'Marshall Rosenberg',
      image: '/courses/nvc.jpg',
      overview: 'Master the four components of NVC: observations, feelings, needs, and requests. Learn empathic listening. Transform judgments into feelings and needs. Handle difficult conversations with grace. Practice self-empathy and self-compassion. Role-play challenging scenarios.',
      notes: 'NVC practice worksheets, feelings/needs inventory, and dialogue examples.',
      totalLessons: 8,
    },
    {
      title: 'Learning How to Learn',
      description: 'Master learning strategies backed by neuroscience. Enhance memory, overcome procrastination, and ace exams with Barbara Oakley.',
      category: 'Learning',
      instructor: 'Dr. Barbara Oakley',
      image: '/courses/learning-to-learn.jpg',
      overview: 'Understand focused and diffuse thinking modes. Learn chunking, spaced repetition, and active recall. Master the Pomodoro Technique for learning. Overcome illusions of competence. Use memory techniques like memory palaces. Understand why sleep is crucial for learning.',
      notes: 'Study technique cheat sheets, practice quizzes, and learning journal templates.',
      totalLessons: 11,
    },
    {
      title: 'Stoic Philosophy for Modern Life',
      description: 'Apply ancient Stoic wisdom to modern challenges. Develop resilience, clarity, and tranquility with Marcus Aurelius, Seneca, and Epictetus.',
      category: 'Philosophy',
      instructor: 'Ryan Holiday',
      image: '/courses/stoicism.jpg',
      overview: 'Learn the core principles of Stoicism: control what you can, accept what you can\'t. Practice negative visualization, voluntary discomfort, and memento mori. Apply Stoic practices to anxiety, anger, and adversity. Study the dichotomy of control and the view from above.',
      notes: 'Daily Stoic journal prompts, virtue exercises, and philosophical reflection guides.',
      totalLessons: 10,
    },
  ];

  for (const course of courses) {
    await courseRepo.save(courseRepo.create(course));
  }

  console.log('✅ Brain tools and resources seeded successfully');
  console.log(`   - ${brainTools.length} brain tools`);
  console.log(`   - ${books.length} books`);
  console.log(`   - ${templates.length} templates`);
  console.log(`   - ${media.length} media items`);
  console.log(`   - ${courses.length} courses`);
};
